name = "acme-web"
compatibility_date = "2025-09-24"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[vars]
VITE_TRPC_URL = "https://acme-server.235trv.workers.dev/trpc"
