/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParksParkCodeRouteImport } from './routes/parks.$parkCode'
import { Route as ParksParkCodeLessonPlansLessonPlanIdRouteImport } from './routes/parks.$parkCode_.lesson-plans.$lessonPlanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksParkCodeRoute = ParksParkCodeRouteImport.update({
  id: '/parks/$parkCode',
  path: '/parks/$parkCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksParkCodeLessonPlansLessonPlanIdRoute =
  ParksParkCodeLessonPlansLessonPlanIdRouteImport.update({
    id: '/parks/$parkCode_/lesson-plans/$lessonPlanId',
    path: '/parks/$parkCode/lesson-plans/$lessonPlanId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parks/$parkCode': typeof ParksParkCodeRoute
  '/parks/$parkCode/lesson-plans/$lessonPlanId': typeof ParksParkCodeLessonPlansLessonPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parks/$parkCode': typeof ParksParkCodeRoute
  '/parks/$parkCode/lesson-plans/$lessonPlanId': typeof ParksParkCodeLessonPlansLessonPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parks/$parkCode': typeof ParksParkCodeRoute
  '/parks/$parkCode_/lesson-plans/$lessonPlanId': typeof ParksParkCodeLessonPlansLessonPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parks/$parkCode'
    | '/parks/$parkCode/lesson-plans/$lessonPlanId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parks/$parkCode' | '/parks/$parkCode/lesson-plans/$lessonPlanId'
  id:
    | '__root__'
    | '/'
    | '/parks/$parkCode'
    | '/parks/$parkCode_/lesson-plans/$lessonPlanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParksParkCodeRoute: typeof ParksParkCodeRoute
  ParksParkCodeLessonPlansLessonPlanIdRoute: typeof ParksParkCodeLessonPlansLessonPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/$parkCode': {
      id: '/parks/$parkCode'
      path: '/parks/$parkCode'
      fullPath: '/parks/$parkCode'
      preLoaderRoute: typeof ParksParkCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/$parkCode_/lesson-plans/$lessonPlanId': {
      id: '/parks/$parkCode_/lesson-plans/$lessonPlanId'
      path: '/parks/$parkCode/lesson-plans/$lessonPlanId'
      fullPath: '/parks/$parkCode/lesson-plans/$lessonPlanId'
      preLoaderRoute: typeof ParksParkCodeLessonPlansLessonPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParksParkCodeRoute: ParksParkCodeRoute,
  ParksParkCodeLessonPlansLessonPlanIdRoute:
    ParksParkCodeLessonPlansLessonPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
