name = "acme-server"
main = "src/index.ts"
compatibility_date = "2025-09-24"
compatibility_flags = ["nodejs_compat"]

# [d1_databases]
# [[d1_databases]]
# binding = "MY_DB"
# database_name = "acme-db"
# database_id = "your-database-id"

[[kv_namespaces]]
# Run: wrangler kv namespace create NPS_CACHE
# Then paste the returned id and preview_id below
binding = "NPS_CACHE"
id = "940e5d8d9a074ed4b44619bcccbf3bc8"
preview_id = "a76cf542bda6450dbcf00a8866c41d20"
